### ISSUE TITLE
21.11-27.11 Настройка докера для базы(Postgres)

### ISSUE THREAD

**Issue by sladinat** [Konstantin200889/AutomationPetProject#2]

**Comment by sladinat** [comment]
Файл типа docker-compose.yml

```yaml
version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
```
